# Generated by Django 4.1.7 on 2024-11-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20210512_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='op4',
        ),
    ]
