# Generated by Django 4.1.7 on 2024-11-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_remove_quesmodel_op4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='ans',
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='correct_option',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Opcja 1'), (2, 'Opcja 2'), (3, 'Opcja 3'), (4, 'Opcja 4')], default=1, verbose_name='Poprawna opcja'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(max_length=200, null=True, verbose_name='Opcja 1'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(max_length=200, null=True, verbose_name='Opcja 2'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op3',
            field=models.CharField(max_length=200, null=True, verbose_name='Opcja 3'),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='question',
            field=models.CharField(max_length=200, null=True, verbose_name='Pytanie'),
        ),
    ]
